### ISSUE TITLE
Quick_beamformer

### ISSUE THREAD

**Issue by WeiKunzhou** [LukasRier/Rier2022_OPM_connectome_test-retest#2]
https://github.com/LukasRier/Rier2022_OPM_connectome_test-retest/blob/67eb100712eda783041648a1ef8106e26770c6c9/Beamformer/full_BF_script.m#L872

**Comment by LukasRier** [comment]
Hi there, full_BF_script.m is legacy code that should not have been included in this repo and is not needed to replicate the analyses in the paper. I will remove this and other similar files in due course.
Quick_beamformer_target_OPM was a 'homemade' function to calculate beamformer weights and is equivalent to the LCMV beamformer you would find in the fieldtrip toolbox (https://www.fieldtriptoolbox.org/) using a single-sphere forward model.
